### PR TITLE
fixes for gcc 11

### PR DESCRIPTION
**Pull request by woodenshoe-wi**
I was able to successfully compile gtktetris using gcc 11.4.0 with these changes.

### CODE REVIEW

**Comment by wader** [comment]
Hey! thanks, what warning/error does it fix?

**Comment by woodenshoe-wi** [comment]
This is only a problem with newer versions of gcc.

Hi @wdlkmpx :smiley:

```
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: multiple definition of `options'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: multiple definition of `next_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: multiple definition of `next_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: multiple definition of `current_lines'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: multiple definition of `current_level'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: multiple definition of `current_score'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: multiple definition of `current_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: multiple definition of `current_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: multiple definition of `current_y'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: multiple definition of `current_x'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: multiple definition of `game_pause'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: multiple definition of `game_over'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: multiple definition of `next_block_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: first defined here
/usr/bin/ld: help.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: multiple definition of `game_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: multiple definition of `options'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: multiple definition of `next_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: multiple definition of `next_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: multiple definition of `current_lines'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: multiple definition of `current_level'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: multiple definition of `current_score'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: multiple definition of `current_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: multiple definition of `current_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: multiple definition of `current_y'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: multiple definition of `current_x'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: multiple definition of `game_pause'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: multiple definition of `game_over'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: multiple definition of `next_block_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: first defined here
/usr/bin/ld: highscore.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: multiple definition of `game_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: multiple definition of `game_over'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: multiple definition of `current_level'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: multiple definition of `options'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: multiple definition of `next_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: multiple definition of `next_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: multiple definition of `game_pause'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: multiple definition of `current_score'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: multiple definition of `current_lines'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: multiple definition of `game_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: multiple definition of `next_block_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: multiple definition of `current_y'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: multiple definition of `current_x'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: multiple definition of `current_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: first defined here
/usr/bin/ld: interface.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: multiple definition of `current_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: multiple definition of `options'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: multiple definition of `next_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: multiple definition of `next_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: multiple definition of `current_lines'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: multiple definition of `current_level'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: multiple definition of `current_score'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: multiple definition of `current_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: multiple definition of `current_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: multiple definition of `current_y'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: multiple definition of `current_x'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: multiple definition of `game_pause'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: multiple definition of `game_over'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: multiple definition of `next_block_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: first defined here
/usr/bin/ld: main.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: multiple definition of `game_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: multiple definition of `options'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: multiple definition of `current_level'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: multiple definition of `next_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: multiple definition of `next_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: multiple definition of `current_lines'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: multiple definition of `current_score'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: multiple definition of `current_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: multiple definition of `current_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: multiple definition of `current_y'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: multiple definition of `current_x'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: multiple definition of `game_pause'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: multiple definition of `game_over'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: multiple definition of `next_block_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: first defined here
/usr/bin/ld: options.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: multiple definition of `game_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: multiple definition of `current_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:45: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: multiple definition of `current_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:46: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: multiple definition of `current_y'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:44: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: multiple definition of `current_x'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:43: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: multiple definition of `next_block'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:50: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: multiple definition of `next_frame'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:51: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: multiple definition of `options'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:76: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: multiple definition of `current_lines'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:49: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: multiple definition of `current_level'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:48: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: multiple definition of `current_score'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:47: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: multiple definition of `game_over'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:41: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: multiple definition of `game_pause'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:42: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: multiple definition of `next_block_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:40: first defined here
/usr/bin/ld: tetris.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: multiple definition of `game_area'; draw.o:/home/woodenshoe/testing git_repos/gtktetris/src/tetris.h:39: first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:17: gtktetris] Error 1
make: *** [Makefile:15: all] Error 1
```

**Comment by wdlkmpx** [comment]
I haven't logged in in a whole year but this change is correct. This should
be merged... I would merge it myself but I'm not logged in

I think I applied something like that,  but somewhere else. Perhaps in
https://github.com/wdlkmpx/wgtkgames/blob/master/GtkTetris/tetris.h

**Comment by wader** [comment]
> I haven't logged in in a whole year but this change is correct. This should be merged... I would merge it myself but I'm not logged in

No worries, i'll merge 👍 ...and now i see, i just had a very quick peek yesterday and thought it was about functions but it's about variables.

**Comment by wader** [comment]
@woodenshoe-wi Thanks!

**Pull request merged**
