### PR TITLE
replace some deprecated functions

### PR DESCRIPTION
**Pull request by wdlkmpx**
these are basically gtk1 functions which are easy to spot and replace

### CODE REVIEW

**Comment by wader** [comment]
Thanks, was a while since i touched and built this code. Do you know if there are other versions with improvments?

**Comment by wdlkmpx** [comment]
I think there are a couple other gtk tetris games on github but i haven't tested them.

This one does work and compiles on Debian Stretch. It also works fine after applying this patch.

The other patch is a bugfix since I  noticed the process keeps running if I don't click on the Quit /Exit menu item.

**Comment by wader** [comment]
Sorry i meant version of my gtktetris, i know there were some patched versions floating around for various distributions etc

**Comment by wdlkmpx** [comment]
It looks like those patches are long gone, this app has become unknown and it was probably dropped from most distros many years ago since I can't  find  info.

**Comment by wdlkmpx** [comment]
I found this:
https://sourceforge.net/projects/gtktetris/files/gtktetris/gtktetris-0.6.2b/

I see the changes from that tarball don't conflict with this PR, and it adds one line that fixes the same bug as #2 .. I'll create a PR that doesn't conflict with #2

**Comment by wdlkmpx** [comment]
Hmm I guess there will be merge conflicts, so PRs must be merged first, it's easy to fix the merge conflicts but I guess PRs must be merged first in order to create clean new PRs...

**Pull request closed without merging**
